### ISSUE TITLE
md-button transclude problem

### ISSUE THREAD

**Issue by vitorghi** [miamarti/simpleGridMaterial#9]
When md-button with a md-icon inside is used you get the following error:
*[ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" ng-click="$ctrl.deleteDraft($index)" aria-label="delete">*

**Comment by miamarti** [comment]
Use a directive, since the transclude problem belongs to the Angular Material component and not to SimpleGlid.

**Solved in** bugfix/Illegal use of ngTransclude directive in the template #10
